debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # ?????

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug # req, res ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: moon
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties: # jpa ???? ?? ??
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true

---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
